name: Deploy to Railway Dev Environment

on:
  push:
    branches: [develop]

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.12.0
      - run: npm install
      - run: npx sequelize db:migrate
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/express_prisma_test?schema=public
      - run: npm test
        env:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/express_prisma_test?schema=public
